site_name: パブリック メモ
site_url: https://uenohajime.github.io/
repo_url: https://github.com/uenohajime/uenohajime.github.io
site_author: Hajime Ueno
theme:
  name: material
  language: ja
google_analytics:
  - G-SKCS56BCRD
  - auto

nav:
  - Home: 'index.md'
  - 'GitHub Actions':
    - 'MkDocs 自動デプロイ': 'actions/mkdocs.md'
