site_name: パブリック メモ
site_url: https://uenohajime.github.io/
repo_url: https://github.com/uenohajime/uenohajime.github.io
site_author: Hajime Ueno
theme:
  name: material
  language: ja
google_analytics:
  - UA-98970296-3
  - auto

nav:
  - Home: 'index.md'
  - 'GitHub Actions':
    - 'MkDocs 自動デプロイ': 'github-actions/mkdocs.md'
  - 'Azure ハンズオン':
    - 'App Service (.NET Core) + SQL Server': 'azure-handson/appservice-sqlserver'
